version: '3.8'

services:
  mt-postgres:
    container_name: mt-postgres
    build:
      context: .
      dockerfile: Dockerfile-PG
    env_file: .env
    ports:
      - "5431:5432"
    networks:
      - my_network
  mt-mysql:
    container_name: mt-mysql
    build:
      context: .
      dockerfile: Dockerfile-MySQL
    env_file: .env
    ports:
      - "3305:3306"
    networks:
      - my_network

networks:
  my_network:
